"""Batch script generation for remote HPC execution.

Generates bash scripts with #SBATCH directives and ASP environment variables
that map decisions and inputs to the script's execution environment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from asp.helpers import get_inputs, get_outputs
from asp.workflow.mapping import apply_naming_convention, extract_decision_values


def generate_batch_script(
    analysis: dict[str, Any],
    universe: dict[str, Any],
    cluster_config: dict[str, Any],
    remote_job_dir: str,
) -> str:
    """Generate a Slurm batch script from an ASP analysis and universe.

    The script:
    - Sets #SBATCH directives from cluster config
    - Exports ASP_DECISION_* env vars for each decision value
    - Exports ASP_INPUT_* env vars for each data input
    - Exports ASP_RESULTS_DIR pointing to the results directory
    - Runs the analysis entry point

    Args:
        analysis: The ASP analysis specification dict.
        universe: The universe dict with decision selections.
        cluster_config: Cluster config from asp-remote.yaml.
        remote_job_dir: Remote directory for this job's files.

    Returns:
        The complete batch script as a string.
    """
    slurm = cluster_config.get("slurm", {})
    python = cluster_config.get("python", "python3")
    universe_id = universe.get("id", "unknown")

    lines: list[str] = []
    lines.append("#!/bin/bash")
    lines.append("")

    # SBATCH directives
    lines.append(f"#SBATCH --job-name=asp-{universe_id}")
    if slurm.get("account") or cluster_config.get("account"):
        lines.append(f"#SBATCH --account={slurm.get('account', cluster_config.get('account'))}")
    if slurm.get("qos"):
        lines.append(f"#SBATCH --qos={slurm['qos']}")
    if slurm.get("constraint"):
        lines.append(f"#SBATCH --constraint={slurm['constraint']}")
    if slurm.get("time"):
        lines.append(f"#SBATCH --time={slurm['time']}")
    if slurm.get("nodes"):
        lines.append(f"#SBATCH --nodes={slurm['nodes']}")
    lines.append(f"#SBATCH --output={remote_job_dir}/slurm-%j.out")
    lines.append(f"#SBATCH --error={remote_job_dir}/slurm-%j.err")
    lines.append("")

    # Header
    lines.append("# Generated by ASP — do not edit")
    lines.append(f"# Universe: {universe_id}")
    lines.append("")

    # Working directory
    lines.append(f"cd {remote_job_dir}")
    lines.append("")

    # ASP decision environment variables
    decision_values = extract_decision_values(analysis, universe)
    if decision_values:
        lines.append("# ASP Decision Variables")
        for decision_id, value in decision_values.items():
            params = apply_naming_convention(decision_id, value)
            for param_name, param_value in params.items():
                env_name = f"ASP_DECISION_{param_name.upper()}"
                lines.append(f"export {env_name}={_shell_quote(param_value)}")
        lines.append("")

    # ASP input environment variables
    data_inputs = [inp for inp in get_inputs(analysis) if inp.get("type") == "data"]
    if data_inputs:
        lines.append("# ASP Input Variables")
        for inp in data_inputs:
            input_id = inp["id"]
            env_name = f"ASP_INPUT_{input_id.upper()}"
            source = inp.get("source", "")
            if isinstance(source, dict):
                # Use path or url from structured source
                source_value = source.get("path") or source.get("url") or ""
            else:
                source_value = str(source) if source else ""
            lines.append(f"export {env_name}={_shell_quote(source_value)}")
        lines.append("")

    # Results directory
    results_dir = f"{remote_job_dir}/results"
    lines.append("# ASP Results Directory")
    lines.append(f"export ASP_RESULTS_DIR={_shell_quote(results_dir)}")
    lines.append(f"mkdir -p $ASP_RESULTS_DIR")
    lines.append("")

    # Output metadata (useful for the script to know what's expected)
    outputs = get_outputs(analysis)
    if outputs:
        lines.append("# Expected outputs:")
        for out in outputs:
            out_id = out.get("id", "")
            out_type = out.get("type", "")
            out_path = out.get("path", "")
            lines.append(f"#   {out_id} ({out_type}): {out_path}")
        lines.append("")

    # Run the analysis
    lines.append("# Run analysis")
    lines.append(f"{python} steps/main.py")
    lines.append("")

    return "\n".join(lines)


def _shell_quote(value: Any) -> str:
    """Quote a value for safe use in a shell script."""
    s = str(value)
    # If it's a simple value (no special chars), no quoting needed
    if s and all(c.isalnum() or c in "._-/" for c in s):
        return s
    # Otherwise, single-quote it (escaping any embedded single quotes)
    return "'" + s.replace("'", "'\\''") + "'"
